-- COMANDO PARA CRIAR UM BANCO DE DADOS
CREATE DATABASE BIBLIOTECA_LEONARDO;
CREATE DATABASE BIBLIOTECA_LEONARDO2;

-- COMANDO PARA APAGAR UM BANCO DE DADOS
DROP DATABASE BIBLIOTECA_LEONARDO2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE BIBLIOTECA_LEONARDO;

-- CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
STATUS_CLIENTE CHAR(10) DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LIVROS (
ID_LIVROS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
QUANTIDADE INT NOT NULL,
TEMA VARCHAR(30),
PRECO DECIMAL(3,2) NOT NULL,
QNTD_PAGINAS INT
);

CREATE TABLE ESTANTE (
ID_ESTANTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
TEMA VARCHAR(30),
QNTD_LIVROS INT NOT NULL,
PRECO DECIMAL(3,2) NOT NULL,
HISTORICO DATETIME
);

CREATE TABLE PEDIDOS (
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
ENDERECO VARCHAR(80) NOT NULL,
QNTD_LIVROS INT NOT NULL,
LIVROS VARCHAR(200) NOT NULL,
PRECO DECIMAL(4,2) NOT NULL
);
